# Site settings
title: Cameron's Blog
email: chenkan@baidu.com
description: > # this means to ignore newlines until "baseurl:"
  Hello Everybody, I'm CHENKAN from China working in Baidu.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://b.chenkan1994.cn" # the base hostname & protocol for your site
twitter_username: chenkan1994
github_username:  chenkan1994

# Build settings
markdown: kramdown
